### ISSUE TITLE
Exception occurred while resuming the order

### ISSUE THREAD

**Issue by fiftin** [spree/spree#6611]
I have tried to login and I have received exception `ActiveRecord::RecordInvalid (Validation failed: Quantity selected of "" is not available.)`
The reason is that stock has no item which is contained in the order.

I have 2 orders with status `address`:
```
 id |   number   |  state   | user_id |        canceled_at         
----+------------+----------+---------+----------------------------
 25 | R503342750 | address  |       1 | 
 21 | R083744486 | address  |       1 | 
```
Order with id `21` has 2 line items:
```
 id | variant_id | quantity | order_id 
----+------------+----------+----------
 37 |         15 |        1 |       21
 36 |         14 |        2 |       21
```
Variant with id `14` has no in the stock. And I receive exception when I try login.

**Comment by fiftin** [comment]
Call stack:
```
ActiveRecord::RecordInvalid (Validation failed: Quantity selected of "" is not available.):
  activerecord (4.2.1) lib/active_record/validations.rb:79:in `raise_record_invalid'
  activerecord (4.2.1) lib/active_record/validations.rb:43:in `save!'
  activerecord (4.2.1) lib/active_record/attribute_methods/dirty.rb:29:in `save!'
  activerecord (4.2.1) lib/active_record/transactions.rb:291:in `block in save!'
  activerecord (4.2.1) lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  activerecord (4.2.1) lib/active_record/transactions.rb:220:in `transaction'
  activerecord (4.2.1) lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
  activerecord (4.2.1) lib/active_record/transactions.rb:291:in `save!'
  spree_core (3.0.0) app/models/spree/order.rb:406:in `block in merge!'
  activerecord (4.2.1) lib/active_record/relation/delegation.rb:46:in `each'
  activerecord (4.2.1) lib/active_record/relation/delegation.rb:46:in `each'
  spree_core (3.0.0) app/models/spree/order.rb:389:in `merge!'
  spree_core (3.0.0) lib/spree/core/controller_helpers/order.rb:61:in `block in set_current_order'
  activerecord (4.2.1) lib/active_record/relation/delegation.rb:46:in `each'
  activerecord (4.2.1) lib/active_record/relation/delegation.rb:46:in `each'
  spree_core (3.0.0) lib/spree/core/controller_helpers/order.rb:60:in `set_current_order'
  activesupport (4.2.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.1) lib/active_support/callbacks.rb:164:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:164:in `block in halting'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
  /home/vtelezhke/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /home/vtelezhke/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /home/vtelezhke/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by fiftin** [comment]
Log:
```
I, [2015-07-21T00:44:15.908908 #28277]  INFO -- : Started POST "/login" for 192.168.0.166 at 2015-07-21 00:44:15 -0400
I, [2015-07-21T00:44:15.911485 #28277]  INFO -- : Processing by Spree::UserSessionsController#create as HTML
I, [2015-07-21T00:44:15.911629 #28277]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"+1Ry+jLZ2Ta0ZiSFevajbBjozuIUFSXHZ9hZ9lNVBH4ECAgx33jij2fy0AYqiYKx5TOnDiq+zzs502OsCiiBOg==", "spree_user"=>{"username"=>"danisvaliullin1989@gmail.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Логин"}
D, [2015-07-21T00:44:15.918289 #28277] DEBUG -- :   Spree::User Load (0.9ms)  SELECT  "spree_users".* FROM "spree_users" WHERE "spree_users"."deleted_at" IS NULL AND (login = 'danisvaliullin1989@gmail.com' OR phone_number = 'danisvaliullin1989@gmail.com' OR lower(email) = lower('danisvaliullin1989@gmail.com'))  ORDER BY "spree_users"."id" ASC LIMIT 1
D, [2015-07-21T00:44:15.921599 #28277] DEBUG -- :   Spree::Order Load (0.5ms)  SELECT "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."guest_token" = $1 AND "spree_orders"."user_id" IS NULL  [["guest_token", "ADztyCJ6Ujrb6zPDS-zJrw"]]
D, [2015-07-21T00:44:15.923795 #28277] DEBUG -- :    (0.2ms)  BEGIN
D, [2015-07-21T00:44:15.926902 #28277] DEBUG -- :   SQL (0.4ms)  UPDATE "spree_users" SET "last_sign_in_at" = $1, "current_sign_in_at" = $2, "sign_in_count" = $3, "updated_at" = $4 WHERE "spree_users"."id" = $5  [["last_sign_in_at", "2015-07-21 04:44:13.489097"], ["current_sign_in_at", "2015-07-21 04:44:15.922559"], ["sign_in_count", 36], ["updated_at", "2015-07-21 04:44:15.924539"], ["id", 1]]
D, [2015-07-21T00:44:15.930097 #28277] DEBUG -- :    (2.0ms)  COMMIT
D, [2015-07-21T00:44:15.932404 #28277] DEBUG -- :   Spree::Store Load (0.5ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE (url like '%xn--b1agaaeye8c.xn--p1ai%')  ORDER BY "spree_stores"."id" ASC LIMIT 1
D, [2015-07-21T00:44:15.933886 #28277] DEBUG -- :   Spree::Store Load (0.4ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE "spree_stores"."default" = 't'  ORDER BY "spree_stores"."id" ASC LIMIT 1
D, [2015-07-21T00:44:15.936229 #28277] DEBUG -- :   Spree::Order Load (0.8ms)  SELECT  "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."completed_at" IS NULL AND "spree_orders"."currency" = $1 AND "spree_orders"."guest_token" = $2 AND "spree_orders"."store_id" = $3 AND "spree_orders"."user_id" = $4 LIMIT 1  [["currency", "RUB"], ["guest_token", "ADztyCJ6Ujrb6zPDS-zJrw"], ["store_id", 1], ["user_id", 1]]
D, [2015-07-21T00:44:15.939859 #28277] DEBUG -- :   Spree::Adjustment Load (0.6ms)  SELECT "spree_adjustments".* FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."adjustable_id" IN (25)  ORDER BY spree_adjustments.created_at ASC
D, [2015-07-21T00:44:15.942597 #28277] DEBUG -- :   Spree::Order Load (0.6ms)  SELECT "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."user_id" = $1 AND "spree_orders"."completed_at" IS NULL AND (id != 25)  [["user_id", 1]]
D, [2015-07-21T00:44:15.945440 #28277] DEBUG -- :   Spree::LineItem Load (0.4ms)  SELECT "spree_line_items".* FROM "spree_line_items" WHERE "spree_line_items"."order_id" = $1  ORDER BY spree_line_items.created_at ASC  [["order_id", 21]]
D, [2015-07-21T00:44:15.948368 #28277] DEBUG -- :   Spree::LineItem Load (0.4ms)  SELECT "spree_line_items".* FROM "spree_line_items" WHERE "spree_line_items"."order_id" = $1  ORDER BY spree_line_items.created_at ASC  [["order_id", 25]]
D, [2015-07-21T00:44:15.950488 #28277] DEBUG -- :   Spree::Variant Load (0.4ms)  SELECT  "spree_variants".* FROM "spree_variants" WHERE "spree_variants"."id" = $1 LIMIT 1  [["id", 207]]
D, [2015-07-21T00:44:15.952439 #28277] DEBUG -- :   Spree::Variant Load (0.4ms)  SELECT  "spree_variants".* FROM "spree_variants" WHERE "spree_variants"."id" = $1 LIMIT 1  [["id", 14]]
D, [2015-07-21T00:44:15.953528 #28277] DEBUG -- :    (0.2ms)  BEGIN
D, [2015-07-21T00:44:15.956184 #28277] DEBUG -- :   Spree::Product Load (0.4ms)  SELECT  "spree_products".* FROM "spree_products" WHERE "spree_products"."id" = $1 LIMIT 1  [["id", 12]]
D, [2015-07-21T00:44:15.958856 #28277] DEBUG -- :   Spree::TaxCategory Load (0.5ms)  SELECT  "spree_tax_categories".* FROM "spree_tax_categories" WHERE "spree_tax_categories"."deleted_at" IS NULL AND "spree_tax_categories"."is_default" = 't'  ORDER BY "spree_tax_categories"."id" ASC LIMIT 1
D, [2015-07-21T00:44:15.961693 #28277] DEBUG -- :    (0.4ms)  SELECT COUNT(*) FROM "spree_inventory_units" WHERE "spree_inventory_units"."line_item_id" = $1  [["line_item_id", 36]]
D, [2015-07-21T00:44:15.965154 #28277] DEBUG -- :    (0.8ms)  SELECT SUM("spree_stock_items"."count_on_hand") FROM "spree_stock_items" INNER JOIN "spree_stock_locations" ON "spree_stock_locations"."id" = "spree_stock_items"."stock_location_id" WHERE "spree_stock_items"."deleted_at" IS NULL AND "spree_stock_items"."variant_id" = 14 AND "spree_stock_locations"."active" = 't'
D, [2015-07-21T00:44:15.966727 #28277] DEBUG -- :   Spree::StockItem Load (0.8ms)  SELECT "spree_stock_items".* FROM "spree_stock_items" INNER JOIN "spree_stock_locations" ON "spree_stock_locations"."id" = "spree_stock_items"."stock_location_id" WHERE "spree_stock_items"."deleted_at" IS NULL AND "spree_stock_items"."variant_id" = 14 AND "spree_stock_locations"."active" = 't'
D, [2015-07-21T00:44:15.969432 #28277] DEBUG -- :   Spree::Product::Translation Load (0.4ms)  SELECT "spree_product_translations".* FROM "spree_product_translations" WHERE "spree_product_translations"."spree_product_id" = $1  [["spree_product_id", 12]]
D, [2015-07-21T00:44:15.973239 #28277] DEBUG -- :   Spree::OptionValue Load (0.5ms)  SELECT "spree_option_values".* FROM "spree_option_values" INNER JOIN "spree_option_values_variants" ON "spree_option_values"."id" = "spree_option_values_variants"."option_value_id" WHERE "spree_option_values_variants"."variant_id" = $1  [["variant_id", 14]]
D, [2015-07-21T00:44:15.975090 #28277] DEBUG -- :    (0.2ms)  ROLLBACK
I, [2015-07-21T00:44:15.975947 #28277]  INFO -- : Completed 422 Unprocessable Entity in 64ms (ActiveRecord: 12.9ms)
F, [2015-07-21T00:44:15.979625 #28277] FATAL -- : 
ActiveRecord::RecordInvalid (Validation failed: Quantity selected of "" is not available.):
```

**Comment by mvz** [comment]
I've had this and similar issues all due to the fact that `Order#merge!` is brittle and will fail catastrophically when any part of it fails. It should probably just drop line items that raise errors.

**Comment by JDutil** [comment]
This should be resolved on master branch https://github.com/spree/spree/commit/d923c10761922801dd2c31b7317877ae0917de6f

**Comment by mvz** [comment]
@JDutil while that changed solved many problems with order resumption, I'm still seeing errors when the `other_order.destroy` fails in `OrderMerger#merge!`.
