### ISSUE TITLE
Spree not working with Rails 5.1

### ISSUE THREAD

**Issue by mayordwells** [spree/spree#7986]
I created a new Rails app using rails -v 5.1.0. 
Used Spree Gems as follows:
gem 'spree', github: 'spree/spree', branch: '3-2-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: 'master'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: 'master'

When I run `bundle` after this I get the following error:
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.1.0)

    spree was resolved to 3.2.1, which depends on
      spree_core (= 3.2.1) was resolved to 3.2.1, which depends on
        rails (~> 5.0.0)

I am running rails 5.1.0 and ruby 2.4.0

What are the possible solutions to this issue? Thanks in advance for your help.

**Comment by damianlegawiec** [comment]
@mayordwells Spree 3.2 is compatible with Rails 5.0, 3.3 (currently `master`) will work on 5.1

**Comment by mayordwells** [comment]
Thanks for your prompt reply @damianlegawiec 
Changed spree branch. 
gem 'spree', github: 'spree/spree', branch: 'master'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: 'master'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: 'master'

bundle install gave the following error: 
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.1.0)

  In Gemfile:
    rails (~> 5.1.0)

    spree was resolved to 3.3.0.beta, which depends on
      spree_frontend (= 3.3.0.beta) was resolved to 3.3.0.beta, which depends on
        canonical-rails (~> 0.2.0) was resolved to 0.2.0, which depends on
          rails (< 5.2, >= 4.1)

    spree was resolved to 3.3.0.beta, which depends on
      spree_core (= 3.3.0.beta) was resolved to 3.3.0.beta, which depends on
        deface (~> 1.0) was resolved to 1.2.0, which depends on
          rails (>= 4.1)

    spree was resolved to 3.3.0.beta, which depends on
      spree_core (= 3.3.0.beta) was resolved to 3.3.0.beta, which depends on
        rails (~> 5.0.0)


And on running bundle update, I got the following errors: 
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    spree_auth_devise was resolved to 3.2.0.beta, which depends on
      devise (~> 4.0.0) was resolved to 4.0.0, which depends on
        railties (< 5.1, >= 4.1.0)

    rails (~> 5.1.0) was resolved to 5.1.0, which depends on
      railties (= 5.1.0)

    sass-rails (~> 5.0) was resolved to 5.0.6, which depends on
      railties (< 6, >= 4.0.0)

    web-console (>= 3.3.0) was resolved to 3.5.0, which depends on
      railties (>= 5.0)

Note: I am running this on a newly created rails v5.1.0 application. 
I have also added 
gem 'devise' in the Gemfile.

**Comment by joshRpowell** [comment]
@mayordwells I've been making incremental PRs preparing Spree for Rails 5.1 I'm still running into failing tests and have not gotten 5.1 to work locally. 

@damianlegawiec do you have Spree `master` working with Rails 5.1?  I would love not to duplicate effort.

**Comment by tathspts** [comment]
hey were you able to make it work? Master resolves to 3.3.0.beta and it is not working. Had to downgrade my rails version.

**Comment by troias** [comment]
I updated gems to 3.2 still not working. Can you please give a better description on how to make spree work in a new rails 5.1 app.

**Comment by krzysiek1507** [comment]
Hi @troias. Spree doesn't work with Rails 5.1. We are working on it

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/8002

**Comment by ninja247** [comment]
@damianlegawiec 

i'm still getting these problems


`
    spree (~> 3.3) was resolved to 3.4.1, which depends on
      spree_core (= 3.4.1) was resolved to 3.4.1, which depends on
        rails (~> 5.1.4)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.`

i'm trying to add the bit pay gem and it's giving me this error

`Bundler could not find compatible versions for gem "spree_core":
  In snapshot (Gemfile.lock):
    spree_core (= 3.4.1)

  In Gemfile:
    spree (~> 3.3) was resolved to 3.4.1, which depends on
      spree_core (= 3.4.1)

    spree (~> 3.3) was resolved to 3.4.1, which depends on
      spree_core (= 3.4.1)

    spree (~> 3.3) was resolved to 3.4.1, which depends on
      spree_core (= 3.4.1)

    spree (~> 3.3) was resolved to 3.4.1, which depends on
      spree_core (= 3.4.1)

    spree (~> 3.3) was resolved to 3.4.1, which depends on
      spree_core (= 3.4.1)

    spree_bitpay (~> 2.0) was resolved to 2.0.0, which depends on
      spree_core (~> 3.0.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.`

**Comment by damianlegawiec** [comment]
@ninja247 

```
spree_bitpay (~> 2.0) was resolved to 2.0.0, which depends on
  spree_core (~> 3.0.1)
```

`spree_bitpay` extension that you are using demands spree at `3.0.1` , you need to update/upgrade this extension to use `3.4`

**Comment by ninja247** [comment]
thanks for replying. do you know who at @bitpay to update their extension?
