### ISSUE TITLE
spree not working with rails 5.1.1

### ISSUE THREAD

**Issue by ditmarbrynza** [spree/spree#8065]
ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

rails -v
Rails 5.1.1

Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.1.1)

  In Gemfile:
    rails (~> 5.1.1)

    spree was resolved to 3.3.0.beta, which depends on
      spree_core (= 3.3.0.beta) was resolved to 3.3.0.beta, which depends on
        rails (~> 5.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

how to solve this problem?

**Comment by damianlegawiec** [comment]
Duplicate of https://github.com/spree/spree/issues/7986

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/8002

**Comment by NemyaNation** [comment]
No it isn't fixed, the same exact errors are still present?

Is this even a working gem?

**Comment by bbonislawski** [comment]
@NemyaNation yes, it works on every version of rails since 4.2. Just use correct version of spree for rails version

**Comment by NemyaNation** [comment]
Rails -> 5.1.4
Ruby -> 2.3.3p222

What versions should I use for this to finally work?

**Comment by bbonislawski** [comment]
https://github.com/spree/spree#rails-51

**Comment by bbonislawski** [comment]
If you encounter errors, please post them. I've set up several applications for tests during last week and everything worked smoothly

**Comment by NemyaNation** [comment]
@bbonislawski 
Created new rails project
Added Gems:
>gem 'spree', '~> 3.4.4'
>gem 'spree_auth_devise', '~> 3.3'
>gem 'spree_gateway', '~> 3.3'

My ruby version:
>ruby 2.3.3p222
My rails version:
>Rails 5.1.4

running bundle update and/or bundle install resulted in the following error
>Errno::EACCES: Permission denied @ rb_file_s_symlink -
(fixtures/ashared/views_rails_3/users/phone_number.json.rabl,
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rabl-0.13.1/fixtures/ashared/views_rails_3/users/phone_number.xml.rabl)
An error occurred while installing rabl (0.13.1), and Bundler
cannot continue.
Make sure that `gem install rabl -v '0.13.1'` succeeds before bundling.
In Gemfile:
  spree was resolved to 3.4.4, which depends on
    spree_backend was resolved to 3.4.4, which depends on

      spree_api was resolved to 3.4.4, which depends on
        rabl



I'm admin with full access to all files, no idea why I keep getting this error.

**Comment by NemyaNation** [comment]
Without the spree gems, rabl installs successfully

**Comment by bbonislawski** [comment]
so you've succesfully ran `gem install rabl -v '0.13.1'` and still getting error?

**Comment by bbonislawski** [comment]
It looks that you're using different ruby version outside of your application and when installing rabl "without spree"

**Comment by NemyaNation** [comment]
No all these commands are from within my application root directory.

I have tried the newest version of rabl, I do not get the ErrNOACCESS error, it's just with the rabl version 0.13.1 do I recieve this error.

Anymore tests you want me to carry out to maybe help solve this faster? I can provide screenshots if needed.

**Comment by bbonislawski** [comment]
so, updating rabl was enough to fix the issue?

**Comment by NemyaNation** [comment]
If I change the version in my gemfile.lock to '0.13.1' , I get the first error again

>ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_file_s_symlink - (fixtures/ashared/views_rails_3/users/phone_number.json.rabl, C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rabl-0.13.1/fixtures/ashared/views_rails_3/users/phone_number.xml.rabl)


when running bundle install with only the following added gems to my gem file
>gem 'spree', '~> 3.4.4'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'

**Comment by bbonislawski** [comment]
It's probably problem with one of your dependencies. Spree 3.4 depends on rabl `~> 0.13.1` so you probably had installed rabl before.

**Comment by NemyaNation** [comment]
This is the same issue posted here, but no help was given.

https://github.com/spree/spree/issues/8059

**Comment by NemyaNation** [comment]
@bbonislawski  Uninstall rabl completely and install just that version again?

**Comment by bbonislawski** [comment]
Yeah, try that. It seems that it's problem with rabl only on windows so I cannot even test it since I don't have windows machine

**Comment by NemyaNation** [comment]
@bbonislawski Nope same old error, I will try in the rabl github, I've been having this issue since yesterday and it has really halted process.

**Comment by NemyaNation** [comment]
For anyone in the future having the 
>ERROR: While executing gem ... (Errno::EACCES)
Permission denied @ rb_file_s_symlink - (fixtures/ashared/views_rails_3/users/phone_number.json.rabl, C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rabl-0.13.1/fixtures/ashared/views_rails_3/users/phone_number.xml.rabl)

Error, this is what I did. 

Search cmd, right click, (Run as administrator), gem install rabl -v '0.13.1', and you're done. This took me an embarrassingly long time to figure out...

Thanks for the quick replies @bbonislawski and trying to help me out.

Good luck to you!

**Comment by Alexswansboro** [comment]
Permission denied @ rb_file_s_symlink - (fixtures/ashared/views_rails_3/users/phone_number.json.rabl, C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rabl-0.13.1/fixtures/ashared/views_rails_3/users/phone_number.xml.rabl) 
I am using windows 10 and I am getting this error.  I just tried to install rabl version 0.13.1 in the cmd line as administrator as suggested above.   Any other suggestions
