### ISSUE TITLE
order payment_total is double of total

### ISSUE THREAD

**Issue by Baozi2** [spree/spree#8148]
```
web
spree 3.3.0.rc1
Spree::Config.auto_capture = true
PaymentMethod Spree::Gateway::StripeGateway
```

When place order from web,  when I pay use credit card, I found that the order' payment_total is double of order' total.

**Comment by liangjingyang** [comment]
https://github.com/spree/spree/blob/2-4-stable/core/app/models/spree/order/payments.rb#L56
https://github.com/spree/spree/blob/master/core/app/models/spree/payment.rb#L33

I think the two line above added the payment.amount twice.

But we tried Spree 3-2-stable, it has no this issue. 

And we found under 3-2-stable rails(5.0.4) console, the order is the different object:
```
Running via Spring preloader in process 61713
Loading development environment (Rails 5.0.4)
2.3.3 :001 > o = Spree::Order.last
  Spree::Order Load (0.7ms)  SELECT  "spree_orders".* FROM "spree_orders" ORDER BY "spree_orders"."id" DESC LIMIT ?  [["LIMIT", 1]]
 => #<Spree::Order id: 3, number: "R852593370", item_total: #<BigDecimal:7fef5ef16a58,'0.1599E2',18(27)>, total: #<BigDecimal:7fef5ef167d8,'0.2179E2',18(27)>, state: "complete", adjustment_total: #<BigDecimal:7fef5ef164b8,'0.8E0',9(18)>, user_id: 1, completed_at: "2017-07-19 12:12:20", bill_address_id: 3, ship_address_id: 4, payment_total: #<BigDecimal:7fef5ef158b0,'0.2179E2',18(27)>, shipment_state: "ready", payment_state: "paid", email: "spree@example.com", special_instructions: nil, created_at: "2017-07-19 12:11:28", updated_at: "2017-07-19 12:12:20", currency: "USD", last_ip_address: "127.0.0.1", created_by_id: 1, shipment_total: #<BigDecimal:7fef5ef14550,'0.5E1',9(18)>, additional_tax_total: #<BigDecimal:7fef5ef142d0,'0.8E0',9(18)>, promo_total: #<BigDecimal:7fef5ef14190,'0.0',9(18)>, channel: "spree", included_tax_total: #<BigDecimal:7fef5e823f48,'0.0',9(18)>, item_count: 1, approver_id: nil, approved_at: nil, confirmation_delivered: true, considered_risky: false, guest_token: "mti0RJSC0wpfQNszJS4-iw1500466222689", canceled_at: nil, canceler_id: nil, store_id: 1, state_lock_version: 4, taxable_adjustment_total: #<BigDecimal:7fef5e8237a0,'0.0',9(18)>, non_taxable_adjustment_total: #<BigDecimal:7fef5e823638,'0.0',9(18)>>
2.3.3 :002 > puts o
#<Spree::Order:0x007fef5e07b160>
 => nil
2.3.3 :003 > puts o.payments.first.order
  Spree::Payment Load (0.6ms)  SELECT  "spree_payments".* FROM "spree_payments" WHERE "spree_payments"."order_id" = ? ORDER BY "spree_payments"."created_at" ASC LIMIT ?  [["order_id", 3], ["LIMIT", 1]]
  Spree::Order Load (0.6ms)  SELECT  "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."id" = ? LIMIT ?  [["id", 3], ["LIMIT", 1]]
#<Spree::Order:0x007fef5e013998>
 => nil
```
But under 3.3.0 rc1 rails(5.1.2) console, the order is the same object:
```
Running via Spring preloader in process 78300
Loading development environment (Rails 5.1.2)
2.3.3 :001 > o = Spree::Order.last
  Spree::Order Load (0.3ms)  SELECT  "spree_orders".* FROM "spree_orders" ORDER BY "spree_orders"."id" DESC LIMIT ?  [["LIMIT", 1]]
 => #<Spree::Order id: 3, number: "R913223492", item_total: #<BigDecimal:7f8325ba1c60,'0.1599E2',18(27)>, total: #<BigDecimal:7f8325ba1918,'0.2179E2',18(27)>, state: "complete", adjustment_total: #<BigDecimal:7f8325ba1580,'0.8E0',9(18)>, user_id: 1, completed_at: "2017-07-19 12:20:18", bill_address_id: 3, ship_address_id: 4, payment_total: #<BigDecimal:7f8325ba0900,'0.4358E2',18(27)>, shipment_state: "ready", payment_state: "credit_owed", email: "spree@example.com", special_instructions: nil, created_at: "2017-07-19 12:19:31", updated_at: "2017-07-19 12:20:18", currency: "USD", last_ip_address: "127.0.0.1", created_by_id: 1, shipment_total: #<BigDecimal:7f8325b9b6d0,'0.5E1',9(18)>, additional_tax_total: #<BigDecimal:7f8325b9b220,'0.8E0',9(18)>, promo_total: #<BigDecimal:7f8325b9b0b8,'0.0',9(18)>, channel: "spree", included_tax_total: #<BigDecimal:7f8325b9ae88,'0.0',9(18)>, item_count: 1, approver_id: nil, approved_at: nil, confirmation_delivered: true, considered_risky: false, guest_token: "gCFmGpf96C7_hpCPbIAYVw1500466708434", canceled_at: nil, canceler_id: nil, store_id: 1, state_lock_version: 4, taxable_adjustment_total: #<BigDecimal:7f8325b9a5c8,'0.0',9(18)>, non_taxable_adjustment_total: #<BigDecimal:7f8325b9a208,'0.0',9(18)>>
2.3.3 :002 > puts o
#<Spree::Order:0x007f8325bab2d8>
 => nil
2.3.3 :003 > puts o.payments.first.order
  Spree::Payment Load (0.3ms)  SELECT  "spree_payments".* FROM "spree_payments" WHERE "spree_payments"."order_id" = ? ORDER BY "spree_payments"."created_at" ASC LIMIT ?  [["order_id", 3], ["LIMIT", 1]]
#<Spree::Order:0x007f8325bab2d8>
 => nil
```

I didn't find out this issue, but i hope this can be of some help.

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/8153

**Comment by zhengpd** [comment]
Seeing the same problem when using Spree 3.2.1. About the fix, I think it's a mutual exclusion between 

```ruby
# https://github.com/spree/spree/blob/master/core/app/models/spree/payment.rb#L33
set_callback :save, :after, :update_order, unless: -> { capture_on_dispatch }
```

and 

```ruby
# https://github.com/spree/spree/blob/master/core/app/models/spree/order/payments.rb#L56
self.payment_total += payment.amount
```

since they both update the order's payment_total after a payment completed. So I'm wondering if another fix would be better like:

```ruby
if payment.completed? && payment.capture_on_dispatch
  self.payment_total += payment.amount
end
```

**Comment by zdexter** [comment]
this is still an issue on spree 3.5/3.7/master afaict. I seem to be able to replicate by placing an order using a coupon that results in the order total being greater than the amount the user is asked to pay.

**Comment by Shigawire** [comment]
Same issue with Store Credit payments.

**Comment by zhengpd** [comment]
@akshaysmurthy My idea back then was to get correct payment total ASAP, so suggesting the quick fix like `if payment.completed? && payment.capture_on_dispatch`.  I didn't touch Spree code for a long time, but I take a look on Spree and find that a PR (https://github.com/spree/spree/pull/10516) by @szymoniwacz was merged, which seems a fix for this payment_total bug.

@damianlegawiec This issue can be closed if it's confirmed fixed.
